---
- name: Make sure the binaries directory exists
  ansible.builtin.file:
    path: ~/.local/bin
    state: directory
    mode: "0755"

- name: Copy the background.sh file
  ansible.builtin.copy:
    src: background.sh
    dest: ~/.local/bin
    mode: "0744"

- name: Copy the screensaver.sh file
  ansible.builtin.copy:
    src: screensaver.sh
    dest: ~/.local/bin/
    mode: "0744"

- name: Copy the clone-projects-42.sh file
  ansible.builtin.template:
    src: clone-projects-42.sh.j2
    dest: ~/.local/bin/clone-projects-42.sh
    mode: "0744"

- name: Copy the clone-projects-suckless.sh file
  ansible.builtin.template:
    src: clone-projects-suckless.sh.j2
    dest: ~/.local/bin/clone-projects-suckless.sh
    mode: "0744"

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 et
