---
- name: Install fisher
  ansible.builtin.shell: |
    set -e -o pipefail
    curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
  args:
    creates: ~/.config/fish/functions/fisher.fish
    executable: fish

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 et
