---
- name: Make sure the fish directory exists
  ansible.builtin.file:
    path: ~/.config/fish
    state: directory
    mode: "0755"

- name: Copy the config.fish file
  ansible.builtin.copy:
    src: config.fish
    dest: ~/.config/fish/config.fish
    mode: "0644"

- name: Copy the fish_plugins file
  ansible.builtin.copy:
    src: fish_plugins
    dest: ~/.config/fish/fish_plugins
    mode: "0644"

- name: Make sure the fish/conf.d directory exists
  ansible.builtin.file:
    path: ~/.config/fish/conf.d
    state: directory
    mode: "0755"

- name: Copy the conf.d/gpg-agent.fish file
  ansible.builtin.copy:
    src: conf.d/gpg-agent.fish
    dest: ~/.config/fish/conf.d/gpg-agent.fish
    mode: "0644"

- name: Make sure the fish/functions directory exists
  ansible.builtin.file:
    path: ~/.config/fish/functions
    state: directory
    mode: "0755"

- name: Install fisher plugin manager
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish
    dest: ~/.config/fish/functions/fisher.fish
    mode: "0644"

- name: Copy the asdf repository from github
  ansible.builtin.git:
    repo: git@github.com:asdf-vm/asdf.git
    dest: ~/.asdf
    version: v0.14.0

- name: Make sure the fish/completions directory exists
  ansible.builtin.file:
    path: ~/.config/fish/completions
    state: directory
    mode: "0755"

- name: Symlink asdf.fish completion file
  ansible.builtin.file:
    src: ~/.asdf/completions/asdf.fish
    dest: ~/.config/fish/completions/asdf.fish

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 et
