---
- name: Make sure the directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - ~/.ssh/
    - ~/.ssh/keys/

- name: Copy file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.ssh/{{ item }}"
    mode: "0600"
  loop:
    - config
    - keys/id_ed25519_42
    - keys/id_ed25519_42.pub
    - keys/id_ed25519_codeberg
    - keys/id_ed25519_codeberg.pub
    - keys/id_ed25519_digitalocean
    - keys/id_ed25519_digitalocean.pub
    - keys/id_ed25519_github
    - keys/id_ed25519_github.pub

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 et
