---
- name: Make sure directory exists
  ansible.builtin.file:
    path: ~/.config/picom
    state: directory
    mode: "0755"

- name: Copy picom.conf file
  ansible.builtin.copy:
    src: picom.conf
    dest: ~/.config/picom/picom.conf
    mode: "0644"

# vim: yaml.ansible ts=2 sts=2 sw=2 et
