---
- name: Copy the gtk-2.0 file
  ansible.builtin.copy:
    src: gtkrc-2.0
    dest: ~/.gtkrc-2.0
    mode: "0644"

- name: Copy the gtk-3.0 file
  ansible.builtin.copy:
    src: gtk-3.0.ini
    dest: ~/.config/gtk-3.0/settings.ini
    mode: "0644"

- name: Copy the xsettingsd file
  ansible.builtin.copy:
    src: xsettingsd.conf
    dest: ~/.config/xsettingsd/xsettingsd.conf
    mode: "0644"

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 et
