---
- name: Ensure directory exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - ~/.config/dunst/

- name: Copy file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.config/dunst/{{ item }}"
    mode: "0644"
  loop:
    - dunstrc

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 et
