---
- name: Copy file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "~/.gnupg/{{ item }}"
    mode: "0600"
  loop:
    - gpg.conf
    - gpg-agent.conf

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 et
