---
- name: Copy the gpg.conf file
  ansible.builtin.copy:
    src: gpg.conf
    dest: ~/.gnupg/gpg.conf
    mode: "0600"

- name: Copy the gpg-agent.conf file
  ansible.builtin.copy:
    src: gpg-agent.conf
    dest: ~/.gnupg/gpg-agent.conf
    mode: "0600"

# vim: ft=yaml.ansible ts=2 sts=2 sw=2 et
